export const VALIDATION_CRITERIA = {
    emailMaxLength: 100,
    passwordMinLength: 8,
    passwordMaxLength: 22,
    searchMaxLength: 100,
    searchMinLength: 3,
    nameMinLength: 3,
    nameMaxLength: 30,
    showcaseNameMinLength: 3,
    showcaseNameMaxLength: 40,
    companyNameMinLength: 3,
    companyNameMaxLength: 50,
    companyAddressMinLength: 3,
    companyAddressMaxLength: 100,
    addressMinLength: 3,
    addressMaxLength: 30,
    postalCodeMinLength: 3,
    postalCodeMaxLength: 10,
    locationMinLength: 2,
    locationMaxLength: 280,
  
    titleMinLength: 3,
    titleMaxLength: 40,
    messageMinLength: 3,
    messageMaxLength: 200,
    phoneNoMinLength: 8,
    phoneNoMaxLength: 12,
    discountMinLength: 0,
    discountMaxLength: 3
  };